require "kanji_master/version"
require "kanji_master/constant"
require "kanji_master/regex_constant"
require "kanji_master/prefecture"
require "kanji_master/text"
require "kanji_master/reader"
require "kanji_master/counter"
require "kanji_master/converter"
